# Generated by Django 4.2 on 2023-05-02 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelBase',
            fields=[
                ('id', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('data_criacao', models.DateField(auto_now_add=True, db_column='dt_criacao', null=True, verbose_name='Criado em')),
                ('data_modificacao', models.DateField(auto_now_add=True, db_column='dt_modificacao', null=True, verbose_name='Modificado em')),
            ],
        ),
        migrations.CreateModel(
            name='AcaoDeCorrecao',
            fields=[
                ('modelbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.modelbase')),
                ('titulo', models.CharField(db_column='tx_titulo', max_length=128, verbose_name='Título')),
                ('descricao', models.CharField(db_column='tx_descricao', max_length=128, verbose_name='Descrição')),
                ('tipo', models.CharField(choices=[('NUM', 'Numérico'), ('TXT', 'Texto'), ('DAT', 'Data'), ('MOE', 'Moeda')], db_column='tx_tipo', max_length=3)),
                ('script', models.TextField(db_column='tx_script', verbose_name='Script')),
            ],
            bases=('core.modelbase',),
        ),
        migrations.CreateModel(
            name='Regra',
            fields=[
                ('modelbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.modelbase')),
                ('titulo', models.CharField(db_column='tx_titulo', max_length=128, verbose_name='Título')),
                ('descricao', models.CharField(db_column='tx_descricao', max_length=128, verbose_name='Descrição')),
                ('tipo', models.CharField(choices=[('NUM', 'Numérico'), ('TXT', 'Texto'), ('DAT', 'Data'), ('MOE', 'Moeda')], db_column='tx_tipo', max_length=3)),
                ('script', models.TextField(db_column='tx_script', verbose_name='Script')),
            ],
            bases=('core.modelbase',),
        ),
    ]
