# Generated by Django 4.2 on 2023-06-01 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acaodecorrecao',
            name='codigo',
            field=models.CharField(blank=True, db_column='txt_codigo', max_length=6, unique=True, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='regra',
            name='codigo',
            field=models.CharField(blank=True, db_column='txt_codigo', max_length=6, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='acaodecorrecao',
            name='tipo',
            field=models.CharField(choices=[('INT', 'Numérico Inteiro'), ('TXT', 'Texto'), ('DAT', 'Data'), ('MOE', 'Moeda'), ('DEC', 'Decimal'), ('POR', 'Porcentagem'), ('HOR', 'Hora')], db_column='tx_tipo', max_length=3),
        ),
        migrations.AlterField(
            model_name='regra',
            name='tipo',
            field=models.CharField(choices=[('INT', 'Numérico Inteiro'), ('TXT', 'Texto'), ('DAT', 'Data'), ('MOE', 'Moeda'), ('DEC', 'Decimal'), ('POR', 'Porcentagem'), ('HOR', 'Hora')], db_column='tx_tipo', max_length=3),
        ),
    ]
